version: "3"
services:

  nginx:
    image: orthancteam/orthanc-nginx-certbot:main
    depends_on: [orthanc, orthanc-auth-service]
    restart: unless-stopped
    ports: ["80:80", "443:443"]
    environment:
      ENABLE_ORTHANC: "true"
      ENABLE_KEYCLOAK: "true"
      ENABLE_ORTHANC_TOKEN_SERVICE: "true"
      DOMAIN_NAME: "orthanc-con-2023.orthanc.team"
      CERTBOT_EMAIL: "ops@orthanc.team"
      ENABLE_CLIENT_CERTIFICATE: "true"
    volumes:
      - ./test/ca.crt:/etc/nginx/ssl/ca.crt

  orthanc:
    image: orthancteam/orthanc:25.1.1
    volumes:
      - ./orthanc-admin.jsonc:/etc/orthanc/orthanc-admin.json
      - ./orthanc-common.jsonc:/etc/orthanc/orthanc-common.json
      - orthanc-data:/var/lib/orthanc/db:Z
    restart: unless-stopped
    environment:
      ORTHANC__NAME: "Orthanc"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__STUDY_LIST_SEARCH_MODE: "search-button"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__STUDY_LIST_CONTENT_IF_NO_SEARCH: "empty"
      ORTHANC__ORTHANC_EXPLORER_2__IS_DEFAULT_ORTHANC_UI: "true"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__SHOW_SAME_PATIENT_STUDIES_FILTER: |
        ["PatientBirthDate", "PatientID"]
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      ORTHANC__STONE_WEB_VIEWER__SHOW_INFO_PANEL_AT_STARTUP: "Never"
      ORTHANC__DICOM_WEB__PUBLIC_ROOT: "/orthanc/dicom-web/"
      ORTHANC__DATABASE_SERVER_IDENTIFIER: "orthanc1"
      ORTHANC__POSTGRESQL__ENABLE_INDEX: "true"
      ORTHANC__POSTGRESQL__HOST: "postgres"
      ORTHANC__POSTGRESQL__INDEX_CONNECTIONS_COUNT: 50
      ORTHANC__POSTGRESQL__TRANSACTION_MODE: "ReadCommitted"
      ORTHANC__POSTGRESQL__ENABLE_STORAGE: "false"
    secrets:
      #- postgres-azure.secret.json
      - ORTHANC__AUTHORIZATION__WEB_SERVICE_PASSWORD

  orthanc-for-cert:
    image: orthancteam/orthanc:25.1.1
    volumes:
      - ./orthanc-common.jsonc:/etc/orthanc/orthanc-common.json
      - orthanc-data:/var/lib/orthanc/db:Z
    restart: unless-stopped
    environment:
      ORTHANC__NAME: "Orthanc"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__STUDY_LIST_SEARCH_MODE: "search-button"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__STUDY_LIST_CONTENT_IF_NO_SEARCH: "empty"
      ORTHANC__ORTHANC_EXPLORER_2__IS_DEFAULT_ORTHANC_UI: "true"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__SHOW_SAME_PATIENT_STUDIES_FILTER: |
        ["PatientBirthDate", "PatientID"]
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      ORTHANC__STONE_WEB_VIEWER__SHOW_INFO_PANEL_AT_STARTUP: "Never"
      ORTHANC__DICOM_WEB__PUBLIC_ROOT: "/orthanc-cert/dicom-web/"
      ORTHANC__DATABASE_SERVER_IDENTIFIER: "orthanc2"
      ORTHANC__POSTGRESQL__ENABLE_INDEX: "true"
      ORTHANC__POSTGRESQL__HOST: "postgres"
      ORTHANC__POSTGRESQL__INDEX_CONNECTIONS_COUNT: 10
      ORTHANC__POSTGRESQL__TRANSACTION_MODE: "ReadCommitted"
      ORTHANC__POSTGRESQL__ENABLE_STORAGE: "false"
      ORTHANC__AUTHENTICATION_ENABLED: "false" # because protected by a client cert

  postgres:
    image: postgres:15
    restart: unless-stopped
    volumes: ["orthanc-index:/var/lib/postgresql/data:Z"] 
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  orthanc-auth-service:
    image: orthancteam/orthanc-auth-service:25.1.0
    depends_on: [keycloak]
    restart: unless-stopped
    environment:
      ENABLE_KEYCLOAK: "true"
      PUBLIC_ORTHANC_ROOT: "https://orthanc-con-2023.orthanc.team/orthanc/"
      PUBLIC_LANDING_ROOT: "https://orthanc-con-2023.orthanc.team/orthanc/ui/app/token-landing.html"
      PERMISSIONS_FILE_PATH: "/orthanc_auth_service/permissions.json"
      ENABLE_KEYCLOAK_API_KEYS: "true"
    env_file:
      - ./secrets/orthanc-token.secret.env
    secrets:
      - SECRET_KEY
      - KEYCLOAK_CLIENT_SECRET
    volumes:
      - ./permissions.json:/orthanc_auth_service/permissions.json

  keycloak:
    image: orthancteam/orthanc-keycloak:25.1.0
    depends_on: [keycloak-db]
    restart: unless-stopped
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://keycloak-db:5432/keycloak"
      KC_DB_USERNAME: "keycloak"
      KC_DB_PASSWORD: "keycloak"
      KC_HOSTNAME: "https://orthanc-con-2023.orthanc.team/keycloak"
    env_file:
      - ./secrets/KC_BOOTSTRAP_ADMIN_PASSWORD.env
    # volumes:
    #   - ./favicon.jpg:/opt/keycloak/themes/orthanc/login/resources/img/favicon.ico
    #   - ./logo.jpg:/opt/keycloak/themes/orthanc/login/resources/img/orthanc-logo-text-shadow.png

  keycloak-db:
    image: postgres:15
    restart: unless-stopped
    volumes: ["keycloak-db:/var/lib/postgresql/data"]
    environment:
      POSTGRES_PASSWORD: "keycloak"
      POSTGRES_USER: "keycloak"
      POSTGRES_DB: "keycloak"

volumes:
  keycloak-db:
  orthanc-data:
  orthanc-index:

secrets:
  orthanc-api.secret.json:
    file: secrets/orthanc-api.secret.json
  orthanc-ingest.secret.json:
    file: secrets/orthanc-ingest.secret.json
  orthanc-frontdesk.secret.json:
    file: secrets/orthanc-frontdesk.secret.json
  postgres-azure.secret.json:
    file: secrets/postgres-azure.secret.json
  ORTHANC__AUTHORIZATION__WEB_SERVICE_PASSWORD:
    file: secrets/ORTHANC__AUTHORIZATION__WEB_SERVICE_PASSWORD
  SECRET_KEY:
    file: secrets/SECRET_KEY
  KEYCLOAK_CLIENT_SECRET:
    file: secrets/KEYCLOAK_CLIENT_SECRET

# test