version: "3"
services:

  nginx:
    image: orthancteam/orthanc-nginx-certbot:25.3.0
    depends_on: [orthanc, orthanc-auth-service]
    restart: unless-stopped
    ports: ["80:80", "443:443"]
    environment:
      ENABLE_ORTHANC: "true"
      ENABLE_KEYCLOAK: "true"
      ENABLE_ORTHANC_TOKEN_SERVICE: "false"
      ENABLE_MEDDREAM: "true"
      ENABLE_ORTHANC_FOR_API: "true"
      ENABLE_OHIF: "true"
      DOMAIN_NAME: "demo.orthanc.team"
      CERTBOT_EMAIL: "ops@orthanc.team"

  orthanc:
    image: orthancteam/orthanc:25.4.2
    depends_on: [postgres]
    volumes:
      - ./orthanc-admin.jsonc:/etc/orthanc/orthanc-admin.json
      - orthanc-data:/var/lib/orthanc/db:Z
    restart: unless-stopped
    environment:
      ORTHANC__NAME: "Orthanc"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__STUDY_LIST_SEARCH_MODE: "search-button"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__STUDY_LIST_CONTENT_IF_NO_SEARCH: "empty"
      ORTHANC__ORTHANC_EXPLORER_2__IS_DEFAULT_ORTHANC_UI: "true"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__SHOW_SAME_PATIENT_STUDIES_FILTER: |
        ["PatientBirthDate", "PatientID"]
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      ORTHANC__STONE_WEB_VIEWER__SHOW_INFO_PANEL_AT_STARTUP: "Never"
      ORTHANC__DICOM_WEB__PUBLIC_ROOT: "/orthanc/dicom-web/"
      ORTHANC__DATABASE_SERVER_IDENTIFIER: "orthanc1"
      ORTHANC__POSTGRESQL__ENABLE_INDEX: "true"
      ORTHANC__POSTGRESQL__HOST: "postgres"
      ORTHANC__POSTGRESQL__INDEX_CONNECTIONS_COUNT: 50
      ORTHANC__POSTGRESQL__TRANSACTION_MODE: "ReadCommitted"
      ORTHANC__POSTGRESQL__ENABLE_STORAGE: "false"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__MED_DREAM_VIEWER_PUBLIC_ROOT: "https://demo.orthanc.team/meddream/"
      ORTHANC__DICOM_MODALITIES: |
        {
            "OLD-PACS": ["OLD-PACS", "192.168.1.222", 50000],
            "SYNGOVIA": ["SYNGOVIA", "192.168.1.223", 50002]
        }
    secrets:
      - ORTHANC__AUTHORIZATION__WEB_SERVICE_PASSWORD


  postgres:
    image: postgres:16
    restart: unless-stopped
    volumes: ["orthanc-index:/var/lib/postgresql/data:Z"] 
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  orthanc-auth-service:
    image: orthancteam/orthanc-auth-service:25.3.0
    depends_on: [keycloak]
    restart: unless-stopped
    environment:
      ENABLE_KEYCLOAK: "true"
      PUBLIC_ORTHANC_ROOT: "https://demo.orthanc.team/orthanc/"
      PUBLIC_LANDING_ROOT: "https://demo.orthanc.team/orthanc/ui/app/token-landing.html"
      PERMISSIONS_FILE_PATH: "/orthanc_auth_service/permissions.json"
      ENABLE_KEYCLOAK_API_KEYS: "true"
      PUBLIC_OHIF_ROOT: "https://demo.orthanc.team/ohif/"
    env_file:
      - ./secrets/orthanc-token.secret.env
    secrets:
      - SECRET_KEY
      - KEYCLOAK_CLIENT_SECRET
    volumes:
      - ./permissions.json:/orthanc_auth_service/permissions.json

  ohif:
    image: orthancteam/ohif-v3:25.3.0
#  uncomment if you want to customize ohif configuration
#    volumes:
#      - ./ohif-app-config.js:/usr/share/nginx/html/app-config.js
    restart: unless-stopped

  meddream-token-service:
    image: orthancteam/meddream-token-service:25.3.0
    restart: unless-stopped

  meddream-viewer:
    image: orthancteam/meddream-viewer:25.3.0
    restart: unless-stopped
    depends_on:
      - orthanc-for-api
    environment:
      integration: "study"
      TOKEN_SERVICE_ADDRESS: "http://meddream-token-service:8088/v3/validate"
      ORTHANC_BASE_URL: "http://orthanc-for-api:8042"
      ORTHANC_USER: "meddream-user"
      MEDDREAM_PACS_CONFIG_TYPE: "Dicomweb"
    env_file:
      - ./secrets/meddream.secret.env
    volumes:
      - meddream-license:/opt/meddream/license

  # An orthanc dedicated for API accesses and also used by MedDream
  orthanc-for-api:
    image: orthancteam/orthanc:25.4.2
    volumes:
      - orthanc-data:/var/lib/orthanc/db:Z
    depends_on: [postgres]
    restart: unless-stopped
    environment:
      ORTHANC__NAME: "Orthanc for API"
      ORTHANC__DATABASE_SERVER_IDENTIFIER: "orthanc2"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      ORTHANC__AUTHENTICATION_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC__DICOM_WEB__PUBLIC_ROOT: "/orthanc-api/dicom-web/"
      ORTHANC__POSTGRESQL__HOST: "postgres"
      ORTHANC__POSTGRESQL__INDEX_CONNECTIONS_COUNT: 40
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__MED_DREAM_VIEWER_PUBLIC_ROOT: "https://demo.orthanc.team/meddream/"
    secrets:
      - orthanc-api.secret.json

  keycloak:
    image: orthancteam/orthanc-keycloak:25.3.0
    depends_on: [keycloak-db]
    restart: unless-stopped
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://keycloak-db:5432/keycloak"
      KC_DB_USERNAME: "keycloak"
      KC_DB_PASSWORD: "keycloak"
      KC_HOSTNAME: "https://demo.orthanc.team/keycloak"
    env_file:
      - ./secrets/KC_BOOTSTRAP_ADMIN_PASSWORD.env

  keycloak-db:
    image: postgres:16
    restart: unless-stopped
    volumes: ["keycloak-db:/var/lib/postgresql/data"]
    environment:
      POSTGRES_PASSWORD: "keycloak"
      POSTGRES_USER: "keycloak"
      POSTGRES_DB: "keycloak"

volumes:
  keycloak-db:
  orthanc-data:
  orthanc-index:
  meddream-license:

secrets:
  ORTHANC__AUTHORIZATION__WEB_SERVICE_PASSWORD:
    file: secrets/ORTHANC__AUTHORIZATION__WEB_SERVICE_PASSWORD
  SECRET_KEY:
    file: secrets/SECRET_KEY
  KEYCLOAK_CLIENT_SECRET:
    file: secrets/KEYCLOAK_CLIENT_SECRET
  orthanc-api.secret.json:
    file: secrets/orthanc-api.secret.json
